### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by espidev** [comment]
See https://github.com/flathub/org.kde.angelfish/pull/30 for other changes needed

Currently I don't think angelfish can launch due to a Kirigami bug with glibc assertions enabled

**Comment by Justinzobel** [comment]
I've done some updates on this, it still won't build but I have KF6.1.0 updates pending in MRs:
6.6: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/206
6.7: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/207

**Comment by Justinzobel** [comment]
Correction it wouldn't run due to a QML issue, I added it locally but I assume this is the assert @espidev is referring to:

```
fp run org.kde.angelfish
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
qrc:/qt/qml/org/kde/kirigamiaddons/labs/components/SearchPopupField.qml:419:17: QML ScrollView: ScrollView only supports Flickable types as its contentItem
qrc:/qt/qml/org/kde/kirigamiaddons/labs/components/SearchPopupField.qml:419:17: QML ScrollView: ScrollView only supports Flickable types as its contentItem
futuresql: Running migration "2022-08-14-223019_init"
futuresql: Running "-- SPDX-FileCopyrightText: 2022 Jonah Brüchert <jbb@kaidan.im>\n--\n-- SPDX-License-Identifier: GPL-2.0-or-later\n\nCREATE TABLE IF NOT EXISTS bookmarks (url TEXT UNIQUE, title TEXT, icon TEXT, lastVisited INT)"
futuresql: Running "CREATE TABLE IF NOT EXISTS history (url TEXT UNIQUE, title TEXT, icon TEXT, lastVisited INT)"
futuresql: Running "CREATE TABLE IF NOT EXISTS icons (url TEXT UNIQUE, icon BLOB)"
futuresql: Running "CREATE UNIQUE INDEX IF NOT EXISTS idx_bookmarks_url ON bookmarks(url)"
futuresql: Running "CREATE UNIQUE INDEX IF NOT EXISTS idx_history_url ON history(url)"
futuresql: Running "CREATE UNIQUE INDEX IF NOT EXISTS idx_icons_url ON icons(url)"
Current tab changed to 0
futuresql: Marking migration "2022-08-14-223019_init" as done.
futuresql: Migrations finished
futuresql: Running "DELETE FROM history WHERE rowid NOT IN (SELECT rowid FROM history ORDER BY lastVisited DESC LIMIT ?)"
futuresql: Running "DELETE FROM icons WHERE url NOT IN (SELECT icon FROM history UNION SELECT icon FROM bookmarks)"
futuresql: Running "SELECT rowid AS id, url, title, icon, ? - lastVisited AS lastVisitedDelta FROM history WHERE url LIKE '%' || ? || '%' OR title LIKE '%' || ? || '%'LIMIT  1000"
Current tab changed to 0
Setting URL: 0 QUrl("https://start.duckduckgo.com") tabs open 1
Wrote to file "/home/justin/.var/app/org.kde.angelfish/config/angelfish/tabs.json" ( 1 urls )
/usr/include/c++/13.2.0/bits/stl_algo.h:3669: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = double]: Assertion '!(__hi < __lo)' failed.
```

**Comment by Justinzobel** [comment]
> Currently crashes with
> 
> ```
> /usr/include/c++/13.2.0/bits/stl_algo.h:3669: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = double]: Assertion '!(__hi < __lo)' failed.
> ```

Yeah we're hoping the KF6.1 update fixes this issue.

**Comment by tsdgeos** [comment]
no backtrace for that crash?

**Comment by Justinzobel** [comment]
bot, build

**Comment by Justinzobel** [comment]
Works here too, looks like KF6.1 fixed it.

**Pull request merged**
