### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by JBBgameich** [comment]
Thank you! You need to update the base-version too, and adapt the Rust Plugin version.

**Comment by travier** [comment]
```
Error: Command 'angelfish' not found
```
🤔

**Comment by tsdgeos** [comment]
The existing json is wrong and the generated-sources.json line needs to be generated/generated-sources.json

**Comment by JBBgameich** [comment]
> The existing json is wrong and the generated-sources.json line needs to be generated/generated-sources.json

This was a workaround for a flatpak-builder bug, I guess it's fixed upstream now.

**Comment by JBBgameich** [comment]
Thanks

**Pull request merged**
